name: Docker image for computational reproducibility

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/carcharhinus-image:${{ github.sha }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/carcharhinus-image:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/carcharhinus-image:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/carcharhinus-image:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/carcharhinus-image:latest
